name: Run tests on PR

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          pip install -r test/test_requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s ./test -p '*_test.py' --verbose
